package: cloud.lazycat.app.redis-commander
version: 0.0.1
name: Redis Commander
description: "Redis Web 端管理工具"
min_os_version: "1.5.0"
homepage: https://github.com/joeferner/redis-commander
author: joeferner
locales:
  zh:
    name: Redis Commander
    description: "Redis Web 端管理工具"
  en:
    name: Redis Commander
    description: "A Redis management tool accessible via browser"
